// app/layout.js
import { Inter } from "next/font/google";
import NavBar from "./components/NavBar";
import AuthCheck from "./customHooks/useAuth";
import "./globals.css";


const inter = Inter({ subsets: ["vietnamese"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthCheck /> {/* Include the AuthCheck component */}
        <NavBar />
        {children}
      </body>
    </html>
  );
}
